dependencies {
    implementation project(':model')
    implementation project(':usecase')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'software.amazon.awssdk:sqs'
    implementation 'org.apache.logging.log4j:log4j-api'
    implementation 'tools.jackson.core:jackson-databind'
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
}
